### ISSUE TITLE
Alt text not being pulled from Statamic Asset Manager

### ISSUE THREAD

**Issue by imbwaldo** [spatie/statamic-responsive-images#74] opened 2021-07-13 16:41 UTC
I'm using this …

`{{ responsive:image alt="{ alt }" }}`

Trying to pull in the alt text entered in the asset itself, but it ain't working. Am I doing something wrong, or is this just not what the Responsive Images addon does?

**Comment by riasvdv** [comment] 2021-07-14 07:01
Have you tried `{{ responsive:image alt="{ image:alt }" }}`?

**Comment by imbwaldo** [comment] 2021-07-14 18:53
Thanks, @riasvdv. Tried that and it didn't work. Does that work for you?

**Comment by jeremylatham** [comment] 2021-07-27 23:06
> Thanks, @riasvdv. Tried that and it didn't work. Does that work for you?

I'm having the same problem.

**Comment by Ceepster14** [comment] 2021-08-09 12:02
Having the same problem. Interestingly on a blog listing page I'm buiilding, if I use the title i.e.  alt="{title}" then the alt tag will contain the blog title, but no joy accessing the alt text entered in the Statamic Asset Manager.

**Comment by josephrlee** [comment] 2021-08-20 02:56
Any updates on a fix for this yet? Thanks!

**Comment by BrianLangevin** [comment] 2021-09-08 00:57
A workaround that I've found for this is to wrap the `responsive` tag in an `asset` tag with an id and container lookup.

```
{{ assets container="assets" :id="image:id" limit="1" }}
    {{ responsive:image :alt="alt" }}
{{ /assets }}
```

Obviously this solution is far from ideal.

**Comment by imbwaldo** [comment] 2021-09-10 21:43
Thanks, @BrianLangevin. That's some workaround!

**Comment by riasvdv** [comment] 2021-09-13 08:40
I'll try to take a look at this either this week or next week, a PR with a fix is certainly welcome as well

**Comment by codedge** [comment] 2021-11-12 18:41
Giving it a little bump 😉 .. running into this as well

**Comment by josephrlee** [comment] 2022-03-22 19:41
Just like to give this another bump. Here's another hacky solution I had to come up with that only works for pages with a single image. I set a bunch of fallbacks on the alt tag. 

`{{ responsive:banner_image ratio="1" sm:ratio="1.5" lg:ratio="1.75" 2xl:ratio="2.25" class="object-cover object-top w-full" alt="{{ banner_image:alt ?? banner_image_seo:alt ?? seo:title }}" }}`

**Comment by imbwaldo** [comment] 2022-03-22 23:57
Sorry, @riasvdv. This remains an issue …

**Comment by imbwaldo** [comment] 2022-03-24 20:35
Hi, @riasvdv.

Would you please reopen this issue? Thanks!

**Closed** 2022-05-23 18:12 UTC
Labels: bug

**Comment by ncla** [comment] 2022-07-01 20:51
Hey @riasvdv,

It seems that the issue is still present. I decided to look at this again after some [folks were talking about this issue again in #addon-support on Statamic Discord server](https://discord.com/channels/489818810157891584/489862989101662218/992500243889406053), and I thought this was fixed too. But unfortunately I could reproduce this issue locally.

There's something funky going with hydration (for lack of better word) I think, if I run `toAugmentedArray` on the `Asset` in `\Spatie\ResponsiveImages\Responsive __construct`, then the alt tag appears as intended. If `toAugmentedArray` is run only  in the `ResponsiveTag` then it is missing the `alt` data (or any data from the data property in the asset .yaml file).

Would you kindly reopen this issue once again? Thanks.

**Comment by riasvdv** [comment] 2022-07-01 21:00
Please open a new one, if you could add a failing test or a small repo with a test app so I can easily reproduce it that would help a lot as well
